argo-cd:
  configs:
    rbac:
      scopes: "[email,groups]"
      policy.csv: |
        g, argocd-admins, role:admin
    cm:
      dex.config: |
        logger:
          level: debug
          format: json
        connectors:
          - type: saml
            id: okta
            name: Okta
            config:
              ssoURL: some-url
              caData: ref+echo://foo/bar
              redirectURI: some-callback-url
              usernameAttr: email
              emailAttr: email
              groupsAttr: groups
      resource.customizations: |
        networking.k8s.io/Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
    params:
      "server.insecure": true # HTTPS is handled by ELB

  redis-ha:
    enabled: true

  controller:
    replicas: 2

  server:
    ingress:
      enabled: true
      ingressClassName: internal-elb
      https: true
      hosts:
        - argocd.elb.staging.k8s
    autoscaling:
      enabled: true
      minReplicas: 2

  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2
